name: Run Tests and Coverage

on:
  pull_request:
  push:
    branches: [ main ]

env:
  MIN_COVERAGE: 80  # <-- variable global

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Setup JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          key:  $ {{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2/repository

      - name: maven-setup
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              { 
                "id": "github", 
                "url": "https://maven.pkg.github.com/pichidev/*",
                "releases": {
                "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: | 
            [
              {
                "id": "github",
                "username": "${{ secrets.READ_PACKAGES_USER }}",
                "password": "${{ secrets.READ_PACKAGES_TOKEN }}"
              }
            ]
          output_file: "${{ github.workspace }}/settings.xml"

      - name: Install, Build and test with maven
        run: mvn -B clean verify -s ${{ github.workspace }}/settings.xml

      - name: Upload Report
        uses: actions/upload-artifact@v5.0.0
        with:
          name: jacoco-report
          path: |
            ${{ github.workspace }}/target/reports/jacoco/jacoco.xml
            ${{ github.workspace }}/target/reports/jacoco/index.html

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/target/reports/jacoco/jacoco.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: ${{ env.MIN_COVERAGE }}
          min-coverage-changed-files: ${{ env.MIN_COVERAGE }}
          title: Code coverage report
      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < env.MIN_COVERAGE || steps.jacoco.outputs.coverage-changed-files < env.MIN_COVERAGE }}
        uses: actions/github-script@v8
        with:
          script: |
            core.setFailed(`Coverage below minimum threshold of ${process.env.MIN_COVERAGE}%!`)

